simple_target_follower:
  ros__parameters:
    publish_rate_hz: 20.0
    expected_target_frame: world
    marker_scale: 0.05
    release_pause_seconds: 1.0
    cut_pause_seconds: 1.0
    first_cycle_start_delay_seconds: 1.0
    cycle_start_delay_seconds: 0.5
    verbose_motion_logs: false
    cycle_busy_topic: "/harvest_cycle_busy"
    cycle_busy_heartbeat_hz: 2.0
    "base_move_joint.source_axis": "x"
    "base_move_joint.zero_world_value": 0.0
    "base_move_joint.scale": 1.0
    "base_move_joint.min": -3.5
    "base_move_joint.max": 3.5
    "base_move_joint.speed": 0.50
    "base_move_joint.initial": 0.0
    "upper_lift_joint.source_axis": "z"
    "upper_lift_joint.zero_world_value": 0.82
    "upper_lift_joint.scale": 1.0
    "upper_lift_joint.min": 0.0
    "upper_lift_joint.max": 0.23
    "upper_lift_joint.speed": 0.30
    "upper_lift_joint.initial": 0.0
    "upper_extend_joint.source_axis": "y"
    "upper_extend_joint.zero_world_value": 0.35
    "upper_extend_joint.scale": -1.0
    "upper_extend_joint.min": -0.37
    "upper_extend_joint.max": 0.0
    "upper_extend_joint.speed": 0.16
    "upper_extend_joint.initial": 0.0
    "lower_lift_joint.source_axis": "z"
    "lower_lift_joint.zero_world_value": 0.82
    "lower_lift_joint.scale": 1.0
    "lower_lift_joint.min": 0.0
    "lower_lift_joint.max": 0.23
    "lower_lift_joint.speed": 0.30
    "lower_lift_joint.initial": 0.0
    "lower_extend_joint.source_axis": "y"
    "lower_extend_joint.zero_world_value": 0.35
    "lower_extend_joint.scale": -1.0
    "lower_extend_joint.min": -0.37
    "lower_extend_joint.max": 0.0
    "lower_extend_joint.speed": 0.16
    "lower_extend_joint.initial": 0.0
